## Load and explore the data

### Import libraries

In [3]:
# Import pandas, numpy, and matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# seaborn as a data visualization library built on matplotlib
import seaborn as sns

# set the plotting style
sns.set_style("whitegrid")

### Load the data

In [5]:
df_seattle = pd.read_csv("/Users/giang/Documents/Data science projects/weather/data/seattle_rain.csv")
df_nyc = pd.read_csv("/Users/giang/Documents/Data science projects/weather/data/nyc_rain.csv")
type(df_seattle)
type(df_nyc)

pandas.core.frame.DataFrame

### Explore the contents of the data sets

In [7]:
df_seattle.head()

,STATION,NAME,DATE,DAPR,MDPR,PRCP,SNOW,SNWD,WESD,WESF
0,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/1/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
1,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/2/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/3/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
3,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/4/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
4,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/5/18,NaN,NaN,0.25,NaN,NaN,NaN,NaN

In [8]:
df_nyc.head()

       STATION                         NAME        DATE  PRCP  SNOW  SNWD
0  USW00094728  NY CITY CENTRAL PARK, NY US  2018-01-01  0.00   0.0   0.0
1  USW00094728  NY CITY CENTRAL PARK, NY US  2018-01-02  0.00   0.0   0.0
2  USW00094728  NY CITY CENTRAL PARK, NY US  2018-01-03  0.00   0.0   0.0
3  USW00094728  NY CITY CENTRAL PARK, NY US  2018-01-04  0.76   9.8   1.2
4  USW00094728  NY CITY CENTRAL PARK, NY US  2018-01-05  0.00   0.0   7.1

In [9]:
df_seattle.columns

Index(['STATION', 'NAME', 'DATE', 'DAPR', 'MDPR', 'PRCP', 'SNOW', 'SNWD',
       'WESD', 'WESF'],
      dtype='object')

In [10]:
df_nyc.columns

Index(['STATION', 'NAME', 'DATE', 'PRCP', 'SNOW', 'SNWD'], dtype='object')

In [11]:
df_seattle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1658 entries, 0 to 1657
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  1658 non-null   object
 1   NAME     1658 non-null   object
 2   DATE     1658 non-null   object
 3   DAPR     23 non-null     float64
 4   MDPR     23 non-null     float64
 5   PRCP     1636 non-null   float64
 6   SNOW     353 non-null    float64
 7   SNWD     66 non-null     float64
 8   WESD     15 non-null     float64
 9   WESF     28 non-null     float64
dtypes: float64(7), object(3)
memory usage: 129.7+ KB

In [12]:
df_nyc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1826 entries, 0 to 1825
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  1826 non-null   object
 1   NAME     1826 non-null   object
 2   DATE     1826 non-null   object
 3   PRCP     1826 non-null   float64
 4   SNOW     1826 non-null   float64
 5   SNWD     1826 non-null   float64
dtypes: float64(3), object(3)
memory usage: 85.7+ KB

In [13]:
print(df_seattle.shape)

(1658, 10)

In [14]:
print(df_nyc.shape)

(1826, 6)

#### Examine the STATION column: how many weather stations are in each data set?

In [16]:
df_seattle['STATION'].nunique()

1

In [17]:
df_nyc['STATION'].nunique()

1

### Convert DATE to datetime

In [19]:
df_seattle['DATE'] = pd.to_datetime(df_seattle['DATE'], format='%m/%d/%y')
df_nyc['DATE'] = pd.to_datetime(df_nyc['DATE'], format='%Y-%m-%d')

In [20]:
df_seattle['DATE']

0      2018-01-01
1      2018-01-02
2      2018-01-03
3      2018-01-04
4      2018-01-05
          ...
1653   2022-12-27
1654   2022-12-28
1655   2022-12-29
1656   2022-12-30
1657   2022-12-31
Name: DATE, Length: 1658, dtype: datetime64[ns]

In [21]:
df_nyc['DATE']

0      2018-01-01
1      2018-01-02
2      2018-01-03
3      2018-01-04
4      2018-01-05
          ...
1821   2022-12-27
1822   2022-12-28
1823   2022-12-29
1824   2022-12-30
1825   2022-12-31
Name: DATE, Length: 1826, dtype: datetime64[ns]

#### What range of dates are present?

In [23]:
df_seattle['DATE'].agg(['min','max'])

min   2018-01-01
max   2022-12-31
Name: DATE, dtype: datetime64[ns]

In [24]:
df_nyc['DATE'].agg(['min','max'])

min   2018-01-01
max   2022-12-31
Name: DATE, dtype: datetime64[ns]

### Check for duplicate and omitted dates

In [26]:
all_dates = pd.date_range('2018-01-01', '2022-12-31')
print('Expected number of days:', len(all_dates))
print('Seattle rows:', df_seattle.shape[0], '| omitted dates:', len(all_dates.difference(df_seattle['DATE'])))
print('NYC rows:    ', df_nyc.shape[0], '| omitted dates:', len(all_dates.difference(df_nyc['DATE'])))
print('Duplicate dates - Seattle:', df_seattle['DATE'].duplicated().sum(), '| NYC:', df_nyc['DATE'].duplicated().sum())

Expected number of days: 1826
Seattle rows: 1658 | omitted dates: 168
NYC rows:     1826 | omitted dates: 0
Duplicate dates - Seattle: 0 | NYC: 0

### Join data frames keeping DATE and PRCP columns

In [28]:
df = df_nyc[['DATE','PRCP']].merge(df_seattle[['DATE','PRCP']], on='DATE', how='outer')
df.head()

        DATE  PRCP_x  PRCP_y
0 2018-01-01    0.00    0.00
1 2018-01-02    0.00    0.00
2 2018-01-03    0.00    0.00
3 2018-01-04    0.76    0.00
4 2018-01-05    0.00    0.25

In [29]:
df.describe()

                      DATE       PRCP_x       PRCP_y
count                 1826  1826.000000  1636.000000
mean   2020-07-01 12:00:00     0.147842     0.111852
min    2018-01-01 00:00:00     0.000000     0.000000
25%    2019-04-02 06:00:00     0.000000     0.000000
50%    2020-07-01 12:00:00     0.000000     0.010000
75%    2021-09-30 18:00:00     0.080000     0.110000
max    2022-12-31 00:00:00     7.130000     2.600000
std                    NaN     0.388334     0.248635

#### Create a tidy data frame with columns for city and precipitation.

In [31]:
# use DATE as the identifier variable
df = pd.melt(df, id_vars='DATE', var_name='city', value_name='precipitation')

In [32]:
df

           DATE    city  precipitation
0    2018-01-01  PRCP_x           0.00
1    2018-01-02  PRCP_x           0.00
2    2018-01-03  PRCP_x           0.00
3    2018-01-04  PRCP_x           0.76
4    2018-01-05  PRCP_x           0.00
...         ...     ...            ...
3647 2022-12-27  PRCP_y           0.78
3648 2022-12-28  PRCP_y           0.40
3649 2022-12-29  PRCP_y           0.03
3650 2022-12-30  PRCP_y           0.62
3651 2022-12-31  PRCP_y           0.17

[3652 rows x 3 columns]

#### Rename columns or values to follow best practices

In [34]:
df.loc[df['city']== 'PRCP_x', 'city'] = 'NYC'
df.loc[df['city']== 'PRCP_y', 'city'] = 'SEA'

In [35]:
df.head()

        DATE city  precipitation
0 2018-01-01  NYC           0.00
1 2018-01-02  NYC           0.00
2 2018-01-03  NYC           0.00
3 2018-01-04  NYC           0.76
4 2018-01-05  NYC           0.00

In [36]:
df.tail()

           DATE city  precipitation
3647 2022-12-27  SEA           0.78
3648 2022-12-28  SEA           0.40
3649 2022-12-29  SEA           0.03
3650 2022-12-30  SEA           0.62
3651 2022-12-31  SEA           0.17

#### Rename the columns to be lowercase using df.rename()

In [38]:
df = df.rename(columns={'DATE': 'date'})
df.head()

        date city  precipitation
0 2018-01-01  NYC           0.00
1 2018-01-02  NYC           0.00
2 2018-01-03  NYC           0.00
3 2018-01-04  NYC           0.76
4 2018-01-05  NYC           0.00

### Identify and fill in missing values

In [40]:
# Count the non-null or null values
df.info()
df.notna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3652 entries, 0 to 3651
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           3652 non-null   datetime64[ns]
 1   city           3652 non-null   object
 2   precipitation  3462 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 85.7+ KB

date             3652
city             3652
precipitation    3462
dtype: int64

#### Determine the number of null values in each column

In [42]:
df.isna().sum()

date               0
city               0
precipitation    190
dtype: int64

#### Determine the number of null precipitation values for Seattle and NYC

In [44]:
df.loc[df['city'] == 'SEA', 'precipitation'].isna().sum()

190

In [45]:
df.loc[df['city'] == 'NYC', 'precipitation'].isna().sum()

0

#### Impute missing values

In [47]:
df['day_of_year'] = pd.DatetimeIndex(df['date']).day_of_year
df.head()

        date city  precipitation  day_of_year
0 2018-01-01  NYC           0.00            1
1 2018-01-02  NYC           0.00            2
2 2018-01-03  NYC           0.00            3
3 2018-01-04  NYC           0.76            4
4 2018-01-05  NYC           0.00            5

#### Compute the mean precipitation for each day in Seattle, averaged across years.

In [49]:
mean_day_precipitation=df.loc[
    df['city']=='SEA',
    ['precipitation','day_of_year']
].groupby(
    'day_of_year'
).mean()

In [50]:
mean_day_precipitation

             precipitation
day_of_year
1                 0.052000
2                 0.150000
3                 0.836000
4                 0.370000
5                 0.246667
...                    ...
362               0.120000
363               0.102000
364               0.268000
365               0.140000
366               0.500000

[366 rows x 1 columns]

In [51]:
# make sure every day of the year has a mean to fill with
mean_day_precipitation['precipitation'].isna().sum()

0

#### Get the index of each row where precipitation is missing.

In [53]:
indices = np.where(df['precipitation'].isna() == True)[0]
indices

array([1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844,
       1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855,
       1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866,
       1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877,
       1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888,
       1889, 1890, 1891, 1892, 1893, 1894, 1895, 2090, 2131, 2132, 2133,
       2134, 2135, 2136, 2137, 2138, 2139, 2140, 2195, 2196, 2197, 2214,
       2215, 2244, 2245, 2246, 2247, 2248, 2249, 2286, 2287, 2288, 2362,
       2363, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377,
       2417, 2418, 2419, 2420, 2421, 2422, 2423, 2517, 2518, 2519, 2520,
       2521, 2522, 2523, 2524, 2559, 2560, 2561, 2602, 2603, 2604, 2605,
       2606, 2607, 2608, 2609, 2610, 2611, 2612, 2818, 2819, 2820, 2821,
       2822, 2823, 2824, 2825, 2826, 2827, 2972, 2973, 2974, 2975, 2983,
       2984, 2986, 2987, 2988, 3000, 3001, 3004, 3005, 3006, 3007, 3008,
       3011, 3012, 3013, 3014, 3015, 3016, 3133, 3134, 3135, 3147, 3148,
       3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159,
       3160, 3161, 3162, 3163, 3363, 3364, 3365, 3366, 3367, 3368, 3369,
       3370, 3371, 3372])

#### Replace each missing value with the mean on that day

In [55]:
# use for loop to iterate in this array
for index in indices:
    df.loc[index,'precipitation'] = mean_day_precipitation.loc[df.loc[index, 'day_of_year']].values[0]

#### Check for missing values in the data frame

In [57]:
df.isna().sum()

date             0
city             0
precipitation    0
day_of_year      0
dtype: int64

In [58]:
df.shape

(3652, 4)

In [59]:
df.groupby('city')['precipitation'].describe()

       count      mean       std  min  25%   50%   75%   max
city
NYC   1826.0  0.147842  0.388334  0.0  0.0  0.00  0.08  7.13
SEA   1826.0  0.113270  0.240516  0.0  0.0  0.01  0.12  2.60

### Export the clean .csv file

In [61]:
df.to_csv('/Users/giang/Documents/Data science projects/weather/data/clean_seattle_nyc_weather.csv', encoding='utf-8-sig', index=False)